name: Auto-update Qomponents Props

on:
  pull_request:
    types: [opened]
    paths:
      - 'package.json'

jobs:
  update-props:
    # Only run on Dependabot PRs that update @seeqdev/qomponents
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, '@seeqdev/qomponents')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate props
        run: npm run generate-props
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit updated props
        if: steps.changes.outputs.no_changes == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: regenerate props after @seeqdev/qomponents update"
          git push
      
      - name: Comment on PR
        if: steps.changes.outputs.no_changes == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Props have been automatically regenerated after the @seeqdev/qomponents update.'
            })
